### ISSUE TITLE
Verifying: bygri

### ISSUE THREAD

**Issue by penny-coin** [penny-coin/validation#127]
Hey there, @bygri, bygri from discord, wants to link this GitHub account.

Continue:
Comment on this issue with the word, `verify`.

**THAT'S NOT ME!**
Comment on this issue with the word, `fraud`.

Something Else:
Type anything else to close this issue.

**Comment by bygri** [comment]
verify

**Comment by penny-coin** [comment]
Have a coin for linking your GitHub! You now have 140 coins.
