### ISSUE TITLE
Verifying: mihaelisaev

### ISSUE THREAD

**Issue by penny-coin** [penny-coin/validation#134]
Hey there, @mihaelisaev, isaev.mihael from slack, wants to link this GitHub account.

Continue:
Comment on this issue with the word, `verify`.

**THAT'S NOT ME!**
Comment on this issue with the word, `fraud`.

Something Else:
Type anything else to close this issue.

**Comment by MihaelIsaev** [comment]
verify

**Comment by penny-coin** [comment]
Have a coin for linking your GitHub! You now have 19 coins.
