### ISSUE TITLE
Verifying: syky

### ISSUE THREAD

**Issue by penny-coin** [penny-coin/validation#178]
Hey there, @syky, syky from discord, wants to link this GitHub account.

Continue:
Comment on this issue with the word, `verify`.

**THAT'S NOT ME!**
Comment on this issue with the word, `fraud`.

Something Else:
Type anything else to close this issue.

**Comment by syky27** [comment]
fraud

**Comment by penny-coin** [comment]
@loganwright, fraud has been reported, please address.
