### ISSUE TITLE
Verifying: PodyDev

### ISSUE THREAD

**Issue by penny-coin** [penny-coin/validation#197]
Hey there, @PodyDev, Pody (｡◕‿◕｡) from discord, wants to link this GitHub account.

Continue:
Comment on this issue with the word, `verify`.

**THAT'S NOT ME!**
Comment on this issue with the word, `fraud`.

Something Else:
Type anything else to close this issue.

**Comment by ghost** [comment]
verify

**Comment by penny-coin** [comment]
Have a coin for linking your GitHub! You now have 1 coins.
