### ISSUE TITLE
Verifying: anthony

### ISSUE THREAD

**Issue by penny-coin** [penny-coin/validation#55]
Hey there, @anthony, anth from discord, wants to link this GitHub account.

Continue:
Comment on this issue with the word, `verify`.

**THAT'S NOT ME!**
Comment on this issue with the word, `fraud`.

Something Else:
Type anything else to close this issue.

**Comment by anthonycastelli** [comment]
verify

**Comment by penny-coin** [comment]
verify

**Comment by anthonycastelli** [comment]
verify

**Comment by anthony** [comment]
fraud

**Comment by penny-coin** [comment]
@loganwright, fraud has been reported, please address.

**Comment by anthonycastelli** [comment]
Pardon me?

**Comment by anthony** [comment]
Apologies if I've misunderstood what is gong on here, but the username mentioned in the original issue is `@anthony` not `@anthonycastelli`

**Comment by anthonycastelli** [comment]
Yes, @Anthony is my discord username being using with @penny-coin. I didn't even realize it mentioned you in the issue

**Comment by anthony** [comment]
@anthonycastelli ah, I see. I got an email because of the `@anthony` in the issue description - sorry for the trouble! 😅
