### ISSUE TITLE
Verifying: dpenny

### ISSUE THREAD

**Issue by penny-coin** [penny-coin/validation#84]
Hey there, @dpenny, dpenny from discord, wants to link this GitHub account.

Continue:
Comment on this issue with the word, `verify`.

**THAT'S NOT ME!**
Comment on this issue with the word, `fraud`.

Something Else:
Type anything else to close this issue.

**Comment by dougpenny** [comment]
verify

**Comment by tanner0101** [comment]
@dpenny-nrca looks like she didn't respond. Try saying verify again

**Comment by dpenny** [comment]
fraud

**Comment by penny-coin** [comment]
@loganwright, fraud has been reported, please address.
